---
swagger: "2.0"
info:
  description: "This is the official Swagger API documentation for Finec Analytics' calc integration"
  version: "1.0.0"
  title: "Finec Analytics"
  termsOfService: "https://www.termsandconditionsgenerator.com/live.php?token=k5sPu3XPnv5Ga3jCN029HrQpIsh3FDYw"
  contact:
    email: "joakim@finecanalytics.se"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "https://o670pc02ti.execute-api.eu-north-1.amazonaws.com"
basePath: "/dev/calc/"
tags:
- name: "Calc"
  description: "Getting calc data"
schemes:
- "https"
- "http"
paths:
  /local:
    get:
      tags:
      - "local calc"
      summary: "Gets calc data from local database"
      description: "---"
      operationId: "----"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Calc"
        401:
          description: "Invalid API key"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
definitions:
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
  Category:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "Category"
  Calc:
    type: "object"
    properties:
      data_id:
        type: "integer"
        format: "int64"
      user_id:
        type: "integer"
        format: "int64"
      sales_date:
        type: "string"
      created:
        type: "string"
      org_social_num:
        type: "string"
      sales_status:
        type: "string"
      return_date_old:
        type: "string"
      return_date:
        type: "string"
      form_name:
        type: "string"
      form_category:
        type: "string"
      office:
        type: "string"
      seller:
        type: "string"
      seller_old:
        type: "string"
      firstname:
        type: "string"
      surname:
        type: "string"
      fullname:
        type: "string"
      customer_address:
        type: "string"
      customer_zip_code:
        type: "integer"
        format: "int64"
      customer_city:
        type: "string"
      total:
        type: "string"
      total_excl_discount:
        type: "string"
      commission:
        type: "string"
      discount:
        type: "string"
      green_tech:
        type: "string"
      information:
        type: "string"
      booker:
        type: "string"
      region:
        type: "string"
      team:
        type: "string"
      cost_center:
        type: "string"
      cost_center_old:
        type: "string"
      group:
        type: "string"
      form_type:
        type: "string"
      token:
        type: "string"
      commission_deduction:
        type: "string"
      project_number:
        type: "string"
      _project_number:
        type: "string"
      project_info:
        type: "string"
      contract_information:
        type: "string"
      project_status:
        type: "string"
      project_comment:
        type: "string"
      project_comment_intern:
        type: "string"
      project__wrong_customer_info:
        type: "string"
      project__wrong_data:
        type: "string"
      project__other:
        type: "string"
      project__revision_agreement:
        type: "string"
      last_edited_by:
        type: "string"
externalDocs:
  description: "Read more about Finec Analytics"
  url: "https://www.finecanalytics.se/"
